version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/conf:/etc/nginx/conf
      - ./nginx/:/etc/nginx/
     #uwsgi_params 
      - ./src/static:/static
    ports:
        - '80:80'
    depends_on: 
        - "web_front"
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=test01
      - POSTGRES_PASSWORD=test01
      - POSTGRES_DB=test01
    ports:
      - "15432:5432"
    depends_on:
      - "nginx"

  rest_api:
    build:
      context: .
      dockerfile: DockerfilePython
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code:code/django_rest_api
    ports:
      - "8000:8000"
    depends_on:
      - db
  web_front:
    build:
      context: .
      dockerfile: DockerfileNode
    volumes:
      - ./code:code/django_web_front
    ports:
      - "3000:3000"